/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

/**
 *
 * @author ASUS GAMER
 */
public class Interfaz_Juego extends javax.swing.JFrame {

    /**
     * Creates new form Interfaz_Inicio
     */
    public Interfaz_Juego() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelPuntuacion = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabelJugador = new javax.swing.JLabel();
        jLabelRonda = new javax.swing.JLabel();
        jLabelIntentos = new javax.swing.JLabel();
        palabraJugador1 = new javax.swing.JTextField();
        letraJugador1 = new javax.swing.JTextField();
        adivinarJugador1 = new javax.swing.JButton();
        jLabelRegresar = new javax.swing.JLabel();
        imagenJugador1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelPuntuacion.setFont(new java.awt.Font("Dialog", 0, 48)); // NOI18N
        jLabelPuntuacion.setText("jLabel2");
        getContentPane().add(jLabelPuntuacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 240, -1, -1));

        jLabel3.setText("Letra");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 450, -1, -1));

        jLabelJugador.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabelJugador.setText("jLabel2");
        getContentPane().add(jLabelJugador, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 120, 380, 50));

        jLabelRonda.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabelRonda.setText("jLabel2");
        getContentPane().add(jLabelRonda, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, 160, 50));

        jLabelIntentos.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabelIntentos.setText("jLabel2");
        getContentPane().add(jLabelIntentos, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 310, 160, 50));

        palabraJugador1.setEnabled(false);
        getContentPane().add(palabraJugador1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 390, 350, -1));
        getContentPane().add(letraJugador1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 480, 50, -1));

        adivinarJugador1.setText("adivinar");
        getContentPane().add(adivinarJugador1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 510, -1, -1));

        jLabelRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/flecha_regresar.png"))); // NOI18N
        jLabelRegresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(jLabelRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 50, 140, 90));

        imagenJugador1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Recurso 1.png"))); // NOI18N
        getContentPane().add(imagenJugador1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 180, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo-blanco-bordes-naranja-1 (2).jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 730));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz_Juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz_Juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz_Juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz_Juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz_Juego().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton adivinarJugador1;
    public javax.swing.JLabel imagenJugador1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    public javax.swing.JLabel jLabelIntentos;
    public javax.swing.JLabel jLabelJugador;
    public javax.swing.JLabel jLabelPuntuacion;
    public javax.swing.JLabel jLabelRegresar;
    public javax.swing.JLabel jLabelRonda;
    public javax.swing.JTextField letraJugador1;
    public javax.swing.JTextField palabraJugador1;
    // End of variables declaration//GEN-END:variables
}
