/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

/**
 *
 * @author ASUS GAMER
 */
public class Interfaz_Resultados extends javax.swing.JFrame {

    /**
     * Creates new form Interfaz_Login
     */
    public Interfaz_Resultados() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelPrimerL = new javax.swing.JLabel();
        jLabelPrimerLP = new javax.swing.JLabel();
        jLabelSegundoL = new javax.swing.JLabel();
        jLabelSegundoLP = new javax.swing.JLabel();
        jLabelTercerL = new javax.swing.JLabel();
        jLabelTercerL1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButtonVolverAJugar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelPrimerL.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabelPrimerL.setText(" ");
        getContentPane().add(jLabelPrimerL, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 190, 310, -1));

        jLabelPrimerLP.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabelPrimerLP.setText(" ");
        getContentPane().add(jLabelPrimerLP, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 250, 360, -1));

        jLabelSegundoL.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabelSegundoL.setText(" ");
        getContentPane().add(jLabelSegundoL, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 370, 310, -1));

        jLabelSegundoLP.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabelSegundoLP.setText(" ");
        getContentPane().add(jLabelSegundoLP, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 430, 310, -1));

        jLabelTercerL.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabelTercerL.setText(" ");
        getContentPane().add(jLabelTercerL, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 340, 280, -1));

        jLabelTercerL1.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabelTercerL1.setText(" ");
        getContentPane().add(jLabelTercerL1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 400, 370, -1));

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 48)); // NOI18N
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/tercerlugar.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 270, 120, 80));

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 48)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/segundolugar.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 300, 130, 70));

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 48)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/primerlugar.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 100, 120, 90));

        jButtonVolverAJugar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/volver-a-publicar.png"))); // NOI18N
        jButtonVolverAJugar.setBorderPainted(false);
        jButtonVolverAJugar.setContentAreaFilled(false);
        jButtonVolverAJugar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonVolverAJugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVolverAJugarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonVolverAJugar, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 480, 150, 80));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo1.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -40, 1100, 640));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonVolverAJugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVolverAJugarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonVolverAJugarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz_Resultados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz_Resultados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz_Resultados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz_Resultados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz_Resultados().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButtonVolverAJugar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    public javax.swing.JLabel jLabelPrimerL;
    public javax.swing.JLabel jLabelPrimerLP;
    public javax.swing.JLabel jLabelSegundoL;
    public javax.swing.JLabel jLabelSegundoLP;
    public javax.swing.JLabel jLabelTercerL;
    public javax.swing.JLabel jLabelTercerL1;
    // End of variables declaration//GEN-END:variables
}
