/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import java.io.File;
import javafx.util.Duration;
import java.util.ArrayList;
import javafx.application.Platform;
import javafx.embed.swing.JFXPanel;
import javafx.scene.media.Media;
import javafx.scene.media.MediaPlayer;
import juegoAhorcado.Resultados;

/**
 *
 * @author ASUS GAMER
 */
public class Interfaz_Menu extends javax.swing.JFrame {

    /**
     * Creates new form Interfaz_Login
     */
    private MediaPlayer mediaPlayer;

      public Interfaz_Menu() {
        // Necesario para inicializar JavaFX en una aplicación Swing
        new JFXPanel(); // Esto asegura que el toolkit de JavaFX esté inicializado

        initComponents();
        Platform.runLater(this::reproducirMusica);
        agregarPuntuaciones();
    }

     private void reproducirMusica() {
        File audioJuego = new File("recursos/juego.mp3");
        Media media = new Media(audioJuego.toURI().toString());
        mediaPlayer = new MediaPlayer(media);
        
        // Añadir un listener para repetir la música cuando finalice
        mediaPlayer.setOnEndOfMedia(() -> mediaPlayer.seek(Duration.ZERO));
        
        mediaPlayer.play();
    }

    public void agregarPuntuaciones() {
        Resultados resultdo = new Resultados(new ArrayList<>());
        resultdo.actualizarJTable("Historial de Jugadores.txt", this);
    }

    public MediaPlayer getMediaPlayer() {
        return this.mediaPlayer;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTablePuntajes = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jButtonJugar = new javax.swing.JButton();
        Saliricono = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTablePuntajes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTablePuntajes.setEnabled(false);
        jTablePuntajes.setFocusable(false);
        jTablePuntajes.setRowSelectionAllowed(false);
        jTablePuntajes.setShowHorizontalLines(false);
        jTablePuntajes.setShowVerticalLines(false);
        jScrollPane1.setViewportView(jTablePuntajes);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 490, 410, 70));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Logotipo.png"))); // NOI18N
        jLabel7.setText("jLabel7");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 80, 710, 190));

        jButtonJugar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/iconjugar.png"))); // NOI18N
        jButtonJugar.setBorder(null);
        jButtonJugar.setBorderPainted(false);
        jButtonJugar.setContentAreaFilled(false);
        jButtonJugar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonJugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonJugarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonJugar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 400, 130, 100));

        Saliricono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/saliricon.png"))); // NOI18N
        Saliricono.setBorderPainted(false);
        Saliricono.setContentAreaFilled(false);
        Saliricono.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Saliricono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaliriconoActionPerformed(evt);
            }
        });
        getContentPane().add(Saliricono, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 420, 110, 80));

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 3, 48)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Salir");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 510, -1, -1));

        jLabel5.setFont(new java.awt.Font("Comic Sans MS", 3, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Puntajes");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 420, -1, -1));

        jLabel6.setFont(new java.awt.Font("Comic Sans MS", 3, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Jugar");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 510, 130, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo1.png"))); // NOI18N
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -40, 1100, 640));

        jLabel3.setText("jLabel2");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonJugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonJugarActionPerformed


    }//GEN-LAST:event_jButtonJugarActionPerformed

    private void SaliriconoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaliriconoActionPerformed

        System.exit(0);
    }//GEN-LAST:event_SaliriconoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz_Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Saliricono;
    public javax.swing.JButton jButtonJugar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable jTablePuntajes;
    // End of variables declaration//GEN-END:variables
}
