/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

/**
 *
 * @author ASUS GAMER
 */
public class Interfaz_Multijugador extends javax.swing.JFrame {

    /**
     * Creates new form Interfaz_Login
     */
    public Interfaz_Multijugador() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jSpinnerRondas = new javax.swing.JSpinner();
        jButtonIniciar = new javax.swing.JButton();
        jButtonAñadir = new javax.swing.JButton();
        jButtonQuitar = new javax.swing.JButton();
        jPanelJugador3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldNombreJugador3 = new javax.swing.JTextField();
        jButtonListo3 = new javax.swing.JButton();
        jPanelJugador1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jButtonListo1 = new javax.swing.JButton();
        jTextFieldNombreJugador1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jPanelJugador4 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextFieldNombreJugador4 = new javax.swing.JTextField();
        jButtonListo4 = new javax.swing.JButton();
        jPanelJugador2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldNombreJugador2 = new javax.swing.JTextField();
        jButtonListo2 = new javax.swing.JButton();
        jLabelRegresar = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 3, 24)); // NOI18N
        jLabel2.setText("Rondas:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 500, -1, -1));

        jSpinnerRondas.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jSpinnerRondas.setToolTipText("");
        jSpinnerRondas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jSpinnerRondas.setValue(1);
        getContentPane().add(jSpinnerRondas, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 500, 70, 30));

        jButtonIniciar.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jButtonIniciar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/iniciar.png"))); // NOI18N
        jButtonIniciar.setBorderPainted(false);
        jButtonIniciar.setContentAreaFilled(false);
        jButtonIniciar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIniciarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonIniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 480, 140, 130));

        jButtonAñadir.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        jButtonAñadir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/agregar.png"))); // NOI18N
        jButtonAñadir.setBorderPainted(false);
        jButtonAñadir.setContentAreaFilled(false);
        jButtonAñadir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(jButtonAñadir, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 40, 80, -1));

        jButtonQuitar.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        jButtonQuitar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/quitarjug.png"))); // NOI18N
        jButtonQuitar.setBorderPainted(false);
        jButtonQuitar.setContentAreaFilled(false);
        jButtonQuitar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonQuitar.setEnabled(false);
        jButtonQuitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonQuitarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonQuitar, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, 110, 80));

        jPanelJugador3.setBackground(new java.awt.Color(153, 204, 255));
        jPanelJugador3.setEnabled(false);
        jPanelJugador3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/foto de perfil generico.png"))); // NOI18N
        jPanelJugador3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 150));

        jLabel8.setText("Nombre");
        jPanelJugador3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));

        jTextFieldNombreJugador3.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextFieldNombreJugador3.setEnabled(false);
        jTextFieldNombreJugador3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNombreJugador3ActionPerformed(evt);
            }
        });
        jPanelJugador3.add(jTextFieldNombreJugador3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 150, -1));

        jButtonListo3.setText("No listo");
        jButtonListo3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonListo3.setEnabled(false);
        jPanelJugador3.add(jButtonListo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 130, -1));

        getContentPane().add(jPanelJugador3, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 190, 170, 270));

        jPanelJugador1.setBackground(new java.awt.Color(153, 204, 255));
        jPanelJugador1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/foto de perfil generico.png"))); // NOI18N
        jPanelJugador1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 150));

        jButtonListo1.setText("No listo");
        jButtonListo1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanelJugador1.add(jButtonListo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 130, -1));

        jTextFieldNombreJugador1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextFieldNombreJugador1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNombreJugador1ActionPerformed(evt);
            }
        });
        jPanelJugador1.add(jTextFieldNombreJugador1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 150, -1));

        jLabel4.setText("Nombre");
        jPanelJugador1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));

        getContentPane().add(jPanelJugador1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, 170, 270));

        jPanelJugador4.setBackground(new java.awt.Color(153, 204, 255));
        jPanelJugador4.setEnabled(false);
        jPanelJugador4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/foto de perfil generico.png"))); // NOI18N
        jPanelJugador4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 150));

        jLabel10.setText("Nombre");
        jPanelJugador4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));

        jTextFieldNombreJugador4.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextFieldNombreJugador4.setEnabled(false);
        jTextFieldNombreJugador4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNombreJugador4ActionPerformed(evt);
            }
        });
        jPanelJugador4.add(jTextFieldNombreJugador4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 150, -1));

        jButtonListo4.setText("No listo");
        jButtonListo4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonListo4.setEnabled(false);
        jPanelJugador4.add(jButtonListo4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 130, -1));

        getContentPane().add(jPanelJugador4, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 190, 170, 270));

        jPanelJugador2.setBackground(new java.awt.Color(153, 204, 255));
        jPanelJugador2.setEnabled(false);
        jPanelJugador2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/foto de perfil generico.png"))); // NOI18N
        jPanelJugador2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 150));

        jLabel6.setText("Nombre");
        jPanelJugador2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));

        jTextFieldNombreJugador2.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextFieldNombreJugador2.setEnabled(false);
        jTextFieldNombreJugador2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNombreJugador2ActionPerformed(evt);
            }
        });
        jPanelJugador2.add(jTextFieldNombreJugador2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 150, -1));

        jButtonListo2.setText("No listo");
        jButtonListo2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonListo2.setEnabled(false);
        jPanelJugador2.add(jButtonListo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 130, -1));

        getContentPane().add(jPanelJugador2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 190, 170, 270));

        jLabelRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/flecha_regresar.png"))); // NOI18N
        jLabelRegresar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jLabelRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 60, 160, 110));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo1.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 640));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIniciarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonIniciarActionPerformed

    private void jTextFieldNombreJugador1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNombreJugador1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNombreJugador1ActionPerformed

    private void jTextFieldNombreJugador2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNombreJugador2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNombreJugador2ActionPerformed

    private void jTextFieldNombreJugador3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNombreJugador3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNombreJugador3ActionPerformed

    private void jTextFieldNombreJugador4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNombreJugador4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNombreJugador4ActionPerformed

    private void jButtonQuitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonQuitarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonQuitarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz_Multijugador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz_Multijugador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz_Multijugador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz_Multijugador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz_Multijugador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButtonAñadir;
    public javax.swing.JButton jButtonIniciar;
    public javax.swing.JButton jButtonListo1;
    public javax.swing.JButton jButtonListo2;
    public javax.swing.JButton jButtonListo3;
    public javax.swing.JButton jButtonListo4;
    public javax.swing.JButton jButtonQuitar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    public javax.swing.JLabel jLabelRegresar;
    public javax.swing.JPanel jPanelJugador1;
    public javax.swing.JPanel jPanelJugador2;
    public javax.swing.JPanel jPanelJugador3;
    public javax.swing.JPanel jPanelJugador4;
    public javax.swing.JSpinner jSpinnerRondas;
    public javax.swing.JTextField jTextFieldNombreJugador1;
    public javax.swing.JTextField jTextFieldNombreJugador2;
    public javax.swing.JTextField jTextFieldNombreJugador3;
    public javax.swing.JTextField jTextFieldNombreJugador4;
    // End of variables declaration//GEN-END:variables
}
